// Copyright (c) 2022 Cascoda Ltd.
// Copyright 2026 NXP
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//      http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
/*
 * @file
 * @brief SPAKE2+ Password-Authenticated Key Exchange for KNX IoT
 *
 * This file implements cryptographic primitives for KNX IoT device authentication.
 *
 * @note Supports two backends:
 * - KNXIOT_SPAKE2P_MBEDTLS: Uses mbedTLS ECP/bignum (legacy)
 * - KNXIOT_SPAKE2P_PSA: Uses PSA Crypto API (recommended, WIP)
 */

#ifndef OC_SPAKE2PLUS_H
#define OC_SPAKE2PLUS_H

#ifdef KNXIOT_SPAKE2P_MBEDTLS
#include "mbedtls/bignum.h"
#include "mbedtls/ecp.h"
#elif defined(KNXIOT_SPAKE2P_PSA)
// In mbedTLS v4.0, ECP and bignum function declarations moved to private headers.
// These are only needed for the mbedTLS-based SPAKE2+ fallback. Platforms with a
// PSA SPAKE2+ driver don't need these private headers.
#if defined(MBEDTLS_DECLARE_PRIVATE_IDENTIFIERS)
#include <mbedtls/private/bignum.h>
#include <mbedtls/private/ecp.h>
#else
#include <mbedtls/bignum.h>
#include <mbedtls/ecp.h>
#endif //MBEDTLS_DECLARE_PRIVATE_IDENTIFIERS
#endif

#include "oc_helpers.h"
#include "oscore_constants.h"

/**
 * @brief Public key size for SPAKE2+ using P-256 curve
 * Format: 1 byte (0x04 uncompressed) + 32 bytes X + 32 bytes Y = 65 bytes
 */
enum { kPubKeySize = 65 };

/**
 * @brief SPAKE2+ protocol data structure
 * @warning Contains sensitive cryptographic material.
 *          - Must be zeroed after use with oc_spake_free()
 *          - Never log or transmit y or K_main
 *          - Store only in secure memory
 */
typedef struct
{
  mbedtls_mpi w0;
  mbedtls_ecp_point L;
  mbedtls_mpi y;
  mbedtls_ecp_point pub_y;
  uint8_t K_main[32];
} spake_data_t;

#define SPAKE_CONTEXT "knxpase"

#ifdef __cplusplus
extern "C" {
#endif

/**
 * @brief Initialize Spake2+
 *
 * @return int 0 on success
 */
int oc_spake_init(void);

/**
 * @brief De-initialize Spake2+
 *
 * @return int 0 on success
 */
int oc_spake_free(void);

/**
 * @brief Generate the fields needed for the PASE Parameter Exchange frame type.
 *
 * @ref oc_spake_init() must be called before this function can be used.
 *
 * @param rand Random number
 * @param salt The salt to be used for PBKDF2
 * @return int 0 on success, mbedtls error code on failure
 */
int oc_spake_parameter_exchange(uint8_t* rand, uint8_t* salt);

/**
 * @brief get the W0 and L values for SPAKE exchange
 *
 * Uses PBKDF2 with SHA256 & HMAC to calculate a 40-byte output which is
 * converted into w0 and w1.
 *
 * @param salt 32-byte array containing the salt
 * @param it the number of iterations to perform within PBKDF2
 * @param w0 the w0 parameter as defined by SPAKE2+. Must be initialized by the caller.
 * @param L the L parameter as defined by SPAKE2+. Must be initialized by the caller.
 * @return int 0 on success, mbedtls error code on failure
 */
int oc_spake_get_w0_L_params(size_t len_salt, const uint8_t *salt, uint32_t it, mbedtls_mpi* w0, mbedtls_ecp_point* L);

/**
 * @brief Get the currently set Spake2+ password
 * @brief Generate an ECP keypair to be used within the Spake2+ handshake
 *
 * @param y The private part. Do not leak.
 * @param pub_y The public part.
 * @return int 0 on success, mbedtls error code on failure
 */
int oc_spake_gen_keypair(mbedtls_mpi *y, mbedtls_ecp_point *pub_y);

/**
 * @brief Calculate the Public Share of Party A, the Management Client
 *
 * @param shareP Output public share
 * @param pubA Public key generated by Party A
 * @param w0 the w0 parameter, derived using the out-of-band secret
 */
int oc_spake_calc_shareP(mbedtls_ecp_point* shareP, const mbedtls_ecp_point* pubA,
                         const mbedtls_mpi* w0);

/**
 * @brief Calculate the Public Share of Party B, the KNX device
 *
 * @param shareV Output public share
 * @param pubB Public key generated by Party B
 * @param w0 the w0 parameter, derived using the out-of-band secret
 */
int oc_spake_calc_shareV(mbedtls_ecp_point* shareV, const mbedtls_ecp_point* pubB,
                         const mbedtls_mpi *w0);

int oc_spake_encode_pubkey(mbedtls_ecp_point *P, uint8_t out[kPubKeySize]);

/**
 * @brief Calculate the shared secret on the Responder side (the KNX server)
 *
 * @param spake_data SPAKE2+ data structure, after receipt of Credential
 * Exchange message. The output of this function is spake_data.K_main
 * @param shareP_enc The shareP parameter (X) encoded as binary data
 * @param shareV The shareV parameter (Y) encoded as an ECP point
 * @return int 0 on success, mbedtls error code on failure
 */
int oc_spake_calc_transcript_responder(spake_data_t *spake_data,
                                       const uint8_t shareP_enc[kPubKeySize],
                                       mbedtls_ecp_point *shareV);

/**
 * @brief Calculate the key confirmation message sent by the prover
 *
 * @param K_main The main secret
 * @param confirmP Output array to store the result
 * @param bytes_shareV Public key of the verifier
 * @return int 0 on success, mbedtls error otherwise
 */
int oc_spake_calc_confirmP(uint8_t *K_main, uint8_t confirmP[32],
                           uint8_t bytes_shareV[kPubKeySize]);

/**
 * @brief Calculate the key confirmation message sent by the verifier
 *
 * @param K_main The main secret
 * @param confirmV Output array to store the result
 * @param bytes_shareP Public key of the prover
 * @return int 0 on success, mbedtls error otherwise
 */
int oc_spake_calc_confirmV(uint8_t *K_main, uint8_t confirmV[32],
                           uint8_t bytes_shareP[kPubKeySize]);

/**
 * @brief Calculate the shared encryption key from the shared
 * symmetric secret K_main
 *
 * @param K_main The shared secret output by the transcript
 * @param K_shared Output array for the shared encryption key.
 * This is the only output of the protocol that can be used
 * as an encryption key
 * @return int
 */
int oc_spake_calc_K_shared(uint8_t *K_main, uint8_t K_shared[16]);

/**
 * @brief encode value as zero-padded little endian bytes
 *
 * @param value value
 * @param buffer buffer, must be able to fit 8 bytes
 * @return number of bytes written (always 8)
 */
size_t encode_uint(uint64_t value, uint8_t* buffer);


/**
 * @brief  encode string as length followed by bytes
 *
 * @param str string
 * @param buffer buffer, must be able to fit 8 bytes
 * @return number of bytes written
 */
size_t encode_string(const char* str, uint8_t* buffer);


/**
* @brief  point as length followed by bytes
*
* @param group string
* @param point point
* @param buffer buffer, must be able to fit 8 bytes
* @return number of bytes written
*/
size_t encode_point(mbedtls_ecp_group* group, const mbedtls_ecp_point* point, uint8_t* buffer);

int oc_spake_calc_K_shared_256(uint8_t *K_main, uint8_t K_shared[32]);

int calc_transcript_responder(spake_data_t* spake_data, const uint8_t shareP_enc[kPubKeySize], mbedtls_ecp_point* shareV,
                              char* idProver, char* idVerifier, char* context);

int calc_transcript_initiator(mbedtls_mpi* w0, mbedtls_mpi* w1, mbedtls_mpi* x, mbedtls_ecp_point* shareP,
                              const uint8_t shareV_enc[kPubKeySize], uint8_t K_main[32], char* idProver, char* idVerifier,
                              char* context);

#ifdef __cplusplus
}
#endif

#endif